/* tslint:disable */
/* eslint-disable */
/**
 * TeensyRom.Api | v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { TeensyStorageType } from './TeensyStorageType';
import {
  TeensyStorageTypeFromJSON,
  TeensyStorageTypeFromJSONTyped,
  TeensyStorageTypeToJSON,
  TeensyStorageTypeToJSONTyped,
} from './TeensyStorageType';

/**
 *
 * @export
 * @interface CartStorageDto
 */
export interface CartStorageDto {
  /**
   *
   * @type {string}
   * @memberof CartStorageDto
   */
  deviceId: string;
  /**
   *
   * @type {TeensyStorageType}
   * @memberof CartStorageDto
   */
  type: TeensyStorageType;
  /**
   *
   * @type {boolean}
   * @memberof CartStorageDto
   */
  available: boolean;
}

/**
 * Check if a given object implements the CartStorageDto interface.
 */
export function instanceOfCartStorageDto(value: object): value is CartStorageDto {
  if (!('deviceId' in value) || value['deviceId'] === undefined) return false;
  if (!('type' in value) || value['type'] === undefined) return false;
  if (!('available' in value) || value['available'] === undefined) return false;
  return true;
}

export function CartStorageDtoFromJSON(json: any): CartStorageDto {
  return CartStorageDtoFromJSONTyped(json, false);
}

export function CartStorageDtoFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): CartStorageDto {
  if (json == null) {
    return json;
  }
  return {
    deviceId: json['deviceId'],
    type: TeensyStorageTypeFromJSON(json['type']),
    available: json['available'],
  };
}

export function CartStorageDtoToJSON(json: any): CartStorageDto {
  return CartStorageDtoToJSONTyped(json, false);
}

export function CartStorageDtoToJSONTyped(
  value?: CartStorageDto | null,
  ignoreDiscriminator: boolean = false
): any {
  if (value == null) {
    return value;
  }

  return {
    deviceId: value['deviceId'],
    type: TeensyStorageTypeToJSON(value['type']),
    available: value['available'],
  };
}
