/* tslint:disable */
/* eslint-disable */
/**
 * TeensyRom.Api | v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { DeviceState } from './DeviceState';
import {
  DeviceStateFromJSON,
  DeviceStateFromJSONTyped,
  DeviceStateToJSON,
  DeviceStateToJSONTyped,
} from './DeviceState';
import type { CartStorageDto } from './CartStorageDto';
import {
  CartStorageDtoFromJSON,
  CartStorageDtoFromJSONTyped,
  CartStorageDtoToJSON,
  CartStorageDtoToJSONTyped,
} from './CartStorageDto';

/**
 *
 * @export
 * @interface CartDto
 */
export interface CartDto {
  /**
   *
   * @type {string}
   * @memberof CartDto
   */
  deviceId: string;
  /**
   *
   * @type {boolean}
   * @memberof CartDto
   */
  isConnected: boolean;
  /**
   *
   * @type {DeviceState}
   * @memberof CartDto
   */
  deviceState: DeviceState;
  /**
   *
   * @type {string}
   * @memberof CartDto
   */
  comPort: string;
  /**
   *
   * @type {string}
   * @memberof CartDto
   */
  name: string;
  /**
   *
   * @type {string}
   * @memberof CartDto
   */
  fwVersion: string;
  /**
   *
   * @type {boolean}
   * @memberof CartDto
   */
  isCompatible: boolean;
  /**
   *
   * @type {CartStorageDto}
   * @memberof CartDto
   */
  sdStorage: CartStorageDto;
  /**
   *
   * @type {CartStorageDto}
   * @memberof CartDto
   */
  usbStorage: CartStorageDto;
}

/**
 * Check if a given object implements the CartDto interface.
 */
export function instanceOfCartDto(value: object): value is CartDto {
  if (!('deviceId' in value) || value['deviceId'] === undefined) return false;
  if (!('isConnected' in value) || value['isConnected'] === undefined) return false;
  if (!('deviceState' in value) || value['deviceState'] === undefined) return false;
  if (!('comPort' in value) || value['comPort'] === undefined) return false;
  if (!('name' in value) || value['name'] === undefined) return false;
  if (!('fwVersion' in value) || value['fwVersion'] === undefined) return false;
  if (!('isCompatible' in value) || value['isCompatible'] === undefined) return false;
  if (!('sdStorage' in value) || value['sdStorage'] === undefined) return false;
  if (!('usbStorage' in value) || value['usbStorage'] === undefined) return false;
  return true;
}

export function CartDtoFromJSON(json: any): CartDto {
  return CartDtoFromJSONTyped(json, false);
}

export function CartDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): CartDto {
  if (json == null) {
    return json;
  }
  return {
    deviceId: json['deviceId'],
    isConnected: json['isConnected'],
    deviceState: DeviceStateFromJSON(json['deviceState']),
    comPort: json['comPort'],
    name: json['name'],
    fwVersion: json['fwVersion'],
    isCompatible: json['isCompatible'],
    sdStorage: CartStorageDtoFromJSON(json['sdStorage']),
    usbStorage: CartStorageDtoFromJSON(json['usbStorage']),
  };
}

export function CartDtoToJSON(json: any): CartDto {
  return CartDtoToJSONTyped(json, false);
}

export function CartDtoToJSONTyped(
  value?: CartDto | null,
  ignoreDiscriminator: boolean = false
): any {
  if (value == null) {
    return value;
  }

  return {
    deviceId: value['deviceId'],
    isConnected: value['isConnected'],
    deviceState: DeviceStateToJSON(value['deviceState']),
    comPort: value['comPort'],
    name: value['name'],
    fwVersion: value['fwVersion'],
    isCompatible: value['isCompatible'],
    sdStorage: CartStorageDtoToJSON(value['sdStorage']),
    usbStorage: CartStorageDtoToJSON(value['usbStorage']),
  };
}
