/* tslint:disable */
/* eslint-disable */
/**
 * TeensyRom.Api | v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CompetitionDto
 */
export interface CompetitionDto {
    /**
     * 
     * @type {string}
     * @memberof CompetitionDto
     */
    name: string;
    /**
     * 
     * @type {number}
     * @memberof CompetitionDto
     */
    place?: number | null;
}

/**
 * Check if a given object implements the CompetitionDto interface.
 */
export function instanceOfCompetitionDto(value: object): value is CompetitionDto {
    if (!('name' in value) || value['name'] === undefined) return false;
    return true;
}

export function CompetitionDtoFromJSON(json: any): CompetitionDto {
    return CompetitionDtoFromJSONTyped(json, false);
}

export function CompetitionDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): CompetitionDto {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
        'place': json['place'] == null ? undefined : json['place'],
    };
}

export function CompetitionDtoToJSON(json: any): CompetitionDto {
    return CompetitionDtoToJSONTyped(json, false);
}

export function CompetitionDtoToJSONTyped(value?: CompetitionDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'place': value['place'],
    };
}

