/* tslint:disable */
/* eslint-disable */
/**
 * TeensyRom.Api | v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CartDto } from './CartDto';
import {
  CartDtoFromJSON,
  CartDtoFromJSONTyped,
  CartDtoToJSON,
  CartDtoToJSONTyped,
} from './CartDto';

/**
 *
 * @export
 * @interface ConnectDeviceResponse
 */
export interface ConnectDeviceResponse {
  /**
   *
   * @type {CartDto}
   * @memberof ConnectDeviceResponse
   */
  connectedCart: CartDto;
  /**
   *
   * @type {string}
   * @memberof ConnectDeviceResponse
   */
  message: string;
}

/**
 * Check if a given object implements the ConnectDeviceResponse interface.
 */
export function instanceOfConnectDeviceResponse(value: object): value is ConnectDeviceResponse {
  if (!('connectedCart' in value) || value['connectedCart'] === undefined) return false;
  if (!('message' in value) || value['message'] === undefined) return false;
  return true;
}

export function ConnectDeviceResponseFromJSON(json: any): ConnectDeviceResponse {
  return ConnectDeviceResponseFromJSONTyped(json, false);
}

export function ConnectDeviceResponseFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): ConnectDeviceResponse {
  if (json == null) {
    return json;
  }
  return {
    connectedCart: CartDtoFromJSON(json['connectedCart']),
    message: json['message'],
  };
}

export function ConnectDeviceResponseToJSON(json: any): ConnectDeviceResponse {
  return ConnectDeviceResponseToJSONTyped(json, false);
}

export function ConnectDeviceResponseToJSONTyped(
  value?: ConnectDeviceResponse | null,
  ignoreDiscriminator: boolean = false
): any {
  if (value == null) {
    return value;
  }

  return {
    connectedCart: CartDtoToJSON(value['connectedCart']),
    message: value['message'],
  };
}
