/* tslint:disable */
/* eslint-disable */
/**
 * TeensyRom.Api | v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 *
 * @export
 * @interface DeviceStartResponse
 */
export interface DeviceStartResponse {
  /**
   *
   * @type {string}
   * @memberof DeviceStartResponse
   */
  message?: string;
}

/**
 * Check if a given object implements the DeviceStartResponse interface.
 */
export function instanceOfDeviceStartResponse(value: object): value is DeviceStartResponse {
  return true;
}

export function DeviceStartResponseFromJSON(json: any): DeviceStartResponse {
  return DeviceStartResponseFromJSONTyped(json, false);
}

export function DeviceStartResponseFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): DeviceStartResponse {
  if (json == null) {
    return json;
  }
  return {
    message: json['message'] == null ? undefined : json['message'],
  };
}

export function DeviceStartResponseToJSON(json: any): DeviceStartResponse {
  return DeviceStartResponseToJSONTyped(json, false);
}

export function DeviceStartResponseToJSONTyped(
  value?: DeviceStartResponse | null,
  ignoreDiscriminator: boolean = false
): any {
  if (value == null) {
    return value;
  }

  return {
    message: value['message'],
  };
}
