/* tslint:disable */
/* eslint-disable */
/**
 * TeensyRom.Api | v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 */
export const DeviceState = {
  Connected: 'Connected',
  Connectable: 'Connectable',
  ConnectionLost: 'ConnectionLost',
  Busy: 'Busy',
  Unknown: 'Unknown',
} as const;
export type DeviceState = (typeof DeviceState)[keyof typeof DeviceState];

export function instanceOfDeviceState(value: any): boolean {
  for (const key in DeviceState) {
    if (Object.prototype.hasOwnProperty.call(DeviceState, key)) {
      if (DeviceState[key as keyof typeof DeviceState] === value) {
        return true;
      }
    }
  }
  return false;
}

export function DeviceStateFromJSON(json: any): DeviceState {
  return DeviceStateFromJSONTyped(json, false);
}

export function DeviceStateFromJSONTyped(json: any, ignoreDiscriminator: boolean): DeviceState {
  return json as DeviceState;
}

export function DeviceStateToJSON(value?: DeviceState | null): any {
  return value as any;
}

export function DeviceStateToJSONTyped(value: any, ignoreDiscriminator: boolean): DeviceState {
  return value as DeviceState;
}
