/* tslint:disable */
/* eslint-disable */
/**
 * TeensyRom.Api | v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 *
 * @export
 * @interface DeviceStopResponse
 */
export interface DeviceStopResponse {
  /**
   *
   * @type {string}
   * @memberof DeviceStopResponse
   */
  message?: string;
}

/**
 * Check if a given object implements the DeviceStopResponse interface.
 */
export function instanceOfDeviceStopResponse(value: object): value is DeviceStopResponse {
  return true;
}

export function DeviceStopResponseFromJSON(json: any): DeviceStopResponse {
  return DeviceStopResponseFromJSONTyped(json, false);
}

export function DeviceStopResponseFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): DeviceStopResponse {
  if (json == null) {
    return json;
  }
  return {
    message: json['message'] == null ? undefined : json['message'],
  };
}

export function DeviceStopResponseToJSON(json: any): DeviceStopResponse {
  return DeviceStopResponseToJSONTyped(json, false);
}

export function DeviceStopResponseToJSONTyped(
  value?: DeviceStopResponse | null,
  ignoreDiscriminator: boolean = false
): any {
  if (value == null) {
    return value;
  }

  return {
    message: value['message'],
  };
}
