/* tslint:disable */
/* eslint-disable */
/**
 * TeensyRom.Api | v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 *
 * @export
 * @interface DirectoryItemDto
 */
export interface DirectoryItemDto {
  /**
   *
   * @type {string}
   * @memberof DirectoryItemDto
   */
  name: string;
  /**
   *
   * @type {string}
   * @memberof DirectoryItemDto
   */
  path: string;
}

/**
 * Check if a given object implements the DirectoryItemDto interface.
 */
export function instanceOfDirectoryItemDto(value: object): value is DirectoryItemDto {
  if (!('name' in value) || value['name'] === undefined) return false;
  if (!('path' in value) || value['path'] === undefined) return false;
  return true;
}

export function DirectoryItemDtoFromJSON(json: any): DirectoryItemDto {
  return DirectoryItemDtoFromJSONTyped(json, false);
}

export function DirectoryItemDtoFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): DirectoryItemDto {
  if (json == null) {
    return json;
  }
  return {
    name: json['name'],
    path: json['path'],
  };
}

export function DirectoryItemDtoToJSON(json: any): DirectoryItemDto {
  return DirectoryItemDtoToJSONTyped(json, false);
}

export function DirectoryItemDtoToJSONTyped(
  value?: DirectoryItemDto | null,
  ignoreDiscriminator: boolean = false
): any {
  if (value == null) {
    return value;
  }

  return {
    name: value['name'],
    path: value['path'],
  };
}
