/* tslint:disable */
/* eslint-disable */
/**
 * TeensyRom.Api | v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 *
 * @export
 * @interface DisconnectDeviceResponse
 */
export interface DisconnectDeviceResponse {
  /**
   *
   * @type {string}
   * @memberof DisconnectDeviceResponse
   */
  message: string;
}

/**
 * Check if a given object implements the DisconnectDeviceResponse interface.
 */
export function instanceOfDisconnectDeviceResponse(
  value: object
): value is DisconnectDeviceResponse {
  if (!('message' in value) || value['message'] === undefined) return false;
  return true;
}

export function DisconnectDeviceResponseFromJSON(json: any): DisconnectDeviceResponse {
  return DisconnectDeviceResponseFromJSONTyped(json, false);
}

export function DisconnectDeviceResponseFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): DisconnectDeviceResponse {
  if (json == null) {
    return json;
  }
  return {
    message: json['message'],
  };
}

export function DisconnectDeviceResponseToJSON(json: any): DisconnectDeviceResponse {
  return DisconnectDeviceResponseToJSONTyped(json, false);
}

export function DisconnectDeviceResponseToJSONTyped(
  value?: DisconnectDeviceResponse | null,
  ignoreDiscriminator: boolean = false
): any {
  if (value == null) {
    return value;
  }

  return {
    message: value['message'],
  };
}
