/* tslint:disable */
/* eslint-disable */
/**
 * TeensyRom.Api | v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 *
 * @export
 * @interface FileLinkDto
 */
export interface FileLinkDto {
  /**
   *
   * @type {string}
   * @memberof FileLinkDto
   */
  name: string;
  /**
   *
   * @type {string}
   * @memberof FileLinkDto
   */
  url: string;
}

/**
 * Check if a given object implements the FileLinkDto interface.
 */
export function instanceOfFileLinkDto(value: object): value is FileLinkDto {
  if (!('name' in value) || value['name'] === undefined) return false;
  if (!('url' in value) || value['url'] === undefined) return false;
  return true;
}

export function FileLinkDtoFromJSON(json: any): FileLinkDto {
  return FileLinkDtoFromJSONTyped(json, false);
}

export function FileLinkDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): FileLinkDto {
  if (json == null) {
    return json;
  }
  return {
    name: json['name'],
    url: json['url'],
  };
}

export function FileLinkDtoToJSON(json: any): FileLinkDto {
  return FileLinkDtoToJSONTyped(json, false);
}

export function FileLinkDtoToJSONTyped(
  value?: FileLinkDto | null,
  ignoreDiscriminator: boolean = false
): any {
  if (value == null) {
    return value;
  }

  return {
    name: value['name'],
    url: value['url'],
  };
}
