/* tslint:disable */
/* eslint-disable */
/**
 * TeensyRom.Api | v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ViewableItemImageDto } from './ViewableItemImageDto';
import {
    ViewableItemImageDtoFromJSON,
    ViewableItemImageDtoFromJSONTyped,
    ViewableItemImageDtoToJSON,
    ViewableItemImageDtoToJSONTyped,
} from './ViewableItemImageDto';
import type { FileItemType } from './FileItemType';
import {
    FileItemTypeFromJSON,
    FileItemTypeFromJSONTyped,
    FileItemTypeToJSON,
    FileItemTypeToJSONTyped,
} from './FileItemType';

/**
 * 
 * @export
 * @interface FileItemDto
 */
export interface FileItemDto {
    /**
     * 
     * @type {string}
     * @memberof FileItemDto
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof FileItemDto
     */
    path: string;
    /**
     * 
     * @type {number}
     * @memberof FileItemDto
     */
    size: number;
    /**
     * 
     * @type {boolean}
     * @memberof FileItemDto
     */
    isFavorite: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof FileItemDto
     */
    isCompatible: boolean;
    /**
     * 
     * @type {string}
     * @memberof FileItemDto
     */
    title: string;
    /**
     * 
     * @type {string}
     * @memberof FileItemDto
     */
    creator: string;
    /**
     * 
     * @type {string}
     * @memberof FileItemDto
     */
    releaseInfo: string;
    /**
     * 
     * @type {string}
     * @memberof FileItemDto
     */
    description: string;
    /**
     * 
     * @type {string}
     * @memberof FileItemDto
     */
    shareUrl: string;
    /**
     * 
     * @type {string}
     * @memberof FileItemDto
     */
    metadataSource: string;
    /**
     * 
     * @type {string}
     * @memberof FileItemDto
     */
    meta1: string;
    /**
     * 
     * @type {string}
     * @memberof FileItemDto
     */
    meta2: string;
    /**
     * 
     * @type {string}
     * @memberof FileItemDto
     */
    metadataSourcePath: string;
    /**
     * 
     * @type {string}
     * @memberof FileItemDto
     */
    parentPath: string;
    /**
     * 
     * @type {string}
     * @memberof FileItemDto
     */
    playLength: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof FileItemDto
     */
    subtuneLengths: Array<string>;
    /**
     * 
     * @type {number}
     * @memberof FileItemDto
     */
    startSubtuneNum: number;
    /**
     * 
     * @type {Array<ViewableItemImageDto>}
     * @memberof FileItemDto
     */
    images: Array<ViewableItemImageDto>;
    /**
     * 
     * @type {FileItemType}
     * @memberof FileItemDto
     */
    type: FileItemType;
}



/**
 * Check if a given object implements the FileItemDto interface.
 */
export function instanceOfFileItemDto(value: object): value is FileItemDto {
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('path' in value) || value['path'] === undefined) return false;
    if (!('size' in value) || value['size'] === undefined) return false;
    if (!('isFavorite' in value) || value['isFavorite'] === undefined) return false;
    if (!('isCompatible' in value) || value['isCompatible'] === undefined) return false;
    if (!('title' in value) || value['title'] === undefined) return false;
    if (!('creator' in value) || value['creator'] === undefined) return false;
    if (!('releaseInfo' in value) || value['releaseInfo'] === undefined) return false;
    if (!('description' in value) || value['description'] === undefined) return false;
    if (!('shareUrl' in value) || value['shareUrl'] === undefined) return false;
    if (!('metadataSource' in value) || value['metadataSource'] === undefined) return false;
    if (!('meta1' in value) || value['meta1'] === undefined) return false;
    if (!('meta2' in value) || value['meta2'] === undefined) return false;
    if (!('metadataSourcePath' in value) || value['metadataSourcePath'] === undefined) return false;
    if (!('parentPath' in value) || value['parentPath'] === undefined) return false;
    if (!('playLength' in value) || value['playLength'] === undefined) return false;
    if (!('subtuneLengths' in value) || value['subtuneLengths'] === undefined) return false;
    if (!('startSubtuneNum' in value) || value['startSubtuneNum'] === undefined) return false;
    if (!('images' in value) || value['images'] === undefined) return false;
    if (!('type' in value) || value['type'] === undefined) return false;
    return true;
}

export function FileItemDtoFromJSON(json: any): FileItemDto {
    return FileItemDtoFromJSONTyped(json, false);
}

export function FileItemDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): FileItemDto {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
        'path': json['path'],
        'size': json['size'],
        'isFavorite': json['isFavorite'],
        'isCompatible': json['isCompatible'],
        'title': json['title'],
        'creator': json['creator'],
        'releaseInfo': json['releaseInfo'],
        'description': json['description'],
        'shareUrl': json['shareUrl'],
        'metadataSource': json['metadataSource'],
        'meta1': json['meta1'],
        'meta2': json['meta2'],
        'metadataSourcePath': json['metadataSourcePath'],
        'parentPath': json['parentPath'],
        'playLength': json['playLength'],
        'subtuneLengths': json['subtuneLengths'],
        'startSubtuneNum': json['startSubtuneNum'],
        'images': ((json['images'] as Array<any>).map(ViewableItemImageDtoFromJSON)),
        'type': FileItemTypeFromJSON(json['type']),
    };
}

export function FileItemDtoToJSON(json: any): FileItemDto {
    return FileItemDtoToJSONTyped(json, false);
}

export function FileItemDtoToJSONTyped(value?: FileItemDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'path': value['path'],
        'size': value['size'],
        'isFavorite': value['isFavorite'],
        'isCompatible': value['isCompatible'],
        'title': value['title'],
        'creator': value['creator'],
        'releaseInfo': value['releaseInfo'],
        'description': value['description'],
        'shareUrl': value['shareUrl'],
        'metadataSource': value['metadataSource'],
        'meta1': value['meta1'],
        'meta2': value['meta2'],
        'metadataSourcePath': value['metadataSourcePath'],
        'parentPath': value['parentPath'],
        'playLength': value['playLength'],
        'subtuneLengths': value['subtuneLengths'],
        'startSubtuneNum': value['startSubtuneNum'],
        'images': ((value['images'] as Array<any>).map(ViewableItemImageDtoToJSON)),
        'type': FileItemTypeToJSON(value['type']),
    };
}

