/* tslint:disable */
/* eslint-disable */
/**
 * TeensyRom.Api | v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 */
export const FileItemType = {
  Unknown: 'Unknown',
  Song: 'Song',
  Game: 'Game',
  Image: 'Image',
  Hex: 'Hex',
} as const;
export type FileItemType = (typeof FileItemType)[keyof typeof FileItemType];

export function instanceOfFileItemType(value: any): boolean {
  for (const key in FileItemType) {
    if (Object.prototype.hasOwnProperty.call(FileItemType, key)) {
      if (FileItemType[key as keyof typeof FileItemType] === value) {
        return true;
      }
    }
  }
  return false;
}

export function FileItemTypeFromJSON(json: any): FileItemType {
  return FileItemTypeFromJSONTyped(json, false);
}

export function FileItemTypeFromJSONTyped(json: any, ignoreDiscriminator: boolean): FileItemType {
  return json as FileItemType;
}

export function FileItemTypeToJSON(value?: FileItemType | null): any {
  return value as any;
}

export function FileItemTypeToJSONTyped(value: any, ignoreDiscriminator: boolean): FileItemType {
  return value as FileItemType;
}
