/* tslint:disable */
/* eslint-disable */
/**
 * TeensyRom.Api | v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 *
 * @export
 * @interface FileTagDto
 */
export interface FileTagDto {
  /**
   *
   * @type {string}
   * @memberof FileTagDto
   */
  name: string;
  /**
   *
   * @type {string}
   * @memberof FileTagDto
   */
  type: string;
}

/**
 * Check if a given object implements the FileTagDto interface.
 */
export function instanceOfFileTagDto(value: object): value is FileTagDto {
  if (!('name' in value) || value['name'] === undefined) return false;
  if (!('type' in value) || value['type'] === undefined) return false;
  return true;
}

export function FileTagDtoFromJSON(json: any): FileTagDto {
  return FileTagDtoFromJSONTyped(json, false);
}

export function FileTagDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): FileTagDto {
  if (json == null) {
    return json;
  }
  return {
    name: json['name'],
    type: json['type'],
  };
}

export function FileTagDtoToJSON(json: any): FileTagDto {
  return FileTagDtoToJSONTyped(json, false);
}

export function FileTagDtoToJSONTyped(
  value?: FileTagDto | null,
  ignoreDiscriminator: boolean = false
): any {
  if (value == null) {
    return value;
  }

  return {
    name: value['name'],
    type: value['type'],
  };
}
