/* tslint:disable */
/* eslint-disable */
/**
 * TeensyRom.Api | v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CartDto } from './CartDto';
import {
    CartDtoFromJSON,
    CartDtoFromJSONTyped,
    CartDtoToJSON,
    CartDtoToJSONTyped,
} from './CartDto';

/**
 * 
 * @export
 * @interface FindDevicesResponse
 */
export interface FindDevicesResponse {
    /**
     * 
     * @type {Array<CartDto>}
     * @memberof FindDevicesResponse
     */
    devices: Array<CartDto>;
    /**
     * 
     * @type {string}
     * @memberof FindDevicesResponse
     */
    message: string;
}

/**
 * Check if a given object implements the FindDevicesResponse interface.
 */
export function instanceOfFindDevicesResponse(value: object): value is FindDevicesResponse {
    if (!('devices' in value) || value['devices'] === undefined) return false;
    if (!('message' in value) || value['message'] === undefined) return false;
    return true;
}

export function FindDevicesResponseFromJSON(json: any): FindDevicesResponse {
    return FindDevicesResponseFromJSONTyped(json, false);
}

export function FindDevicesResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): FindDevicesResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'devices': ((json['devices'] as Array<any>).map(CartDtoFromJSON)),
        'message': json['message'],
    };
}

export function FindDevicesResponseToJSON(json: any): FindDevicesResponse {
    return FindDevicesResponseToJSONTyped(json, false);
}

export function FindDevicesResponseToJSONTyped(value?: FindDevicesResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'devices': ((value['devices'] as Array<any>).map(CartDtoToJSON)),
        'message': value['message'],
    };
}

