/* tslint:disable */
/* eslint-disable */
/**
 * TeensyRom.Api | v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { StorageCacheDto } from './StorageCacheDto';
import {
  StorageCacheDtoFromJSON,
  StorageCacheDtoFromJSONTyped,
  StorageCacheDtoToJSON,
  StorageCacheDtoToJSONTyped,
} from './StorageCacheDto';

/**
 *
 * @export
 * @interface GetDirectoryResponse
 */
export interface GetDirectoryResponse {
  /**
   *
   * @type {StorageCacheDto}
   * @memberof GetDirectoryResponse
   */
  storageItem: StorageCacheDto;
  /**
   *
   * @type {string}
   * @memberof GetDirectoryResponse
   */
  message: string;
}

/**
 * Check if a given object implements the GetDirectoryResponse interface.
 */
export function instanceOfGetDirectoryResponse(value: object): value is GetDirectoryResponse {
  if (!('storageItem' in value) || value['storageItem'] === undefined) return false;
  if (!('message' in value) || value['message'] === undefined) return false;
  return true;
}

export function GetDirectoryResponseFromJSON(json: any): GetDirectoryResponse {
  return GetDirectoryResponseFromJSONTyped(json, false);
}

export function GetDirectoryResponseFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): GetDirectoryResponse {
  if (json == null) {
    return json;
  }
  return {
    storageItem: StorageCacheDtoFromJSON(json['storageItem']),
    message: json['message'],
  };
}

export function GetDirectoryResponseToJSON(json: any): GetDirectoryResponse {
  return GetDirectoryResponseToJSONTyped(json, false);
}

export function GetDirectoryResponseToJSONTyped(
  value?: GetDirectoryResponse | null,
  ignoreDiscriminator: boolean = false
): any {
  if (value == null) {
    return value;
  }

  return {
    storageItem: StorageCacheDtoToJSON(value['storageItem']),
    message: value['message'],
  };
}
