/* tslint:disable */
/* eslint-disable */
/**
 * TeensyRom.Api | v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface IndexAllResponse
 */
export interface IndexAllResponse {
    /**
     * 
     * @type {string}
     * @memberof IndexAllResponse
     */
    message: string;
}

/**
 * Check if a given object implements the IndexAllResponse interface.
 */
export function instanceOfIndexAllResponse(value: object): value is IndexAllResponse {
    if (!('message' in value) || value['message'] === undefined) return false;
    return true;
}

export function IndexAllResponseFromJSON(json: any): IndexAllResponse {
    return IndexAllResponseFromJSONTyped(json, false);
}

export function IndexAllResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): IndexAllResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'message': json['message'],
    };
}

export function IndexAllResponseToJSON(json: any): IndexAllResponse {
    return IndexAllResponseToJSONTyped(json, false);
}

export function IndexAllResponseToJSONTyped(value?: IndexAllResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'message': value['message'],
    };
}

