/* tslint:disable */
/* eslint-disable */
/**
 * TeensyRom.Api | v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 *
 * @export
 * @interface IndexResponse
 */
export interface IndexResponse {
  /**
   *
   * @type {string}
   * @memberof IndexResponse
   */
  message: string;
}

/**
 * Check if a given object implements the IndexResponse interface.
 */
export function instanceOfIndexResponse(value: object): value is IndexResponse {
  if (!('message' in value) || value['message'] === undefined) return false;
  return true;
}

export function IndexResponseFromJSON(json: any): IndexResponse {
  return IndexResponseFromJSONTyped(json, false);
}

export function IndexResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): IndexResponse {
  if (json == null) {
    return json;
  }
  return {
    message: json['message'],
  };
}

export function IndexResponseToJSON(json: any): IndexResponse {
  return IndexResponseToJSONTyped(json, false);
}

export function IndexResponseToJSONTyped(
  value?: IndexResponse | null,
  ignoreDiscriminator: boolean = false
): any {
  if (value == null) {
    return value;
  }

  return {
    message: value['message'],
  };
}
