/* tslint:disable */
/* eslint-disable */
/**
 * TeensyRom.Api | v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { FileItemDto } from './FileItemDto';
import {
  FileItemDtoFromJSON,
  FileItemDtoFromJSONTyped,
  FileItemDtoToJSON,
  FileItemDtoToJSONTyped,
} from './FileItemDto';

/**
 *
 * @export
 * @interface LaunchRandomResponse
 */
export interface LaunchRandomResponse {
  /**
   *
   * @type {FileItemDto}
   * @memberof LaunchRandomResponse
   */
  launchedFile: FileItemDto;
  /**
   *
   * @type {string}
   * @memberof LaunchRandomResponse
   */
  message: string;
  /**
   *
   * @type {boolean}
   * @memberof LaunchRandomResponse
   */
  isCompatible: boolean;
}

/**
 * Check if a given object implements the LaunchRandomResponse interface.
 */
export function instanceOfLaunchRandomResponse(value: object): value is LaunchRandomResponse {
  if (!('launchedFile' in value) || value['launchedFile'] === undefined) return false;
  if (!('message' in value) || value['message'] === undefined) return false;
  if (!('isCompatible' in value) || value['isCompatible'] === undefined) return false;
  return true;
}

export function LaunchRandomResponseFromJSON(json: any): LaunchRandomResponse {
  return LaunchRandomResponseFromJSONTyped(json, false);
}

export function LaunchRandomResponseFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): LaunchRandomResponse {
  if (json == null) {
    return json;
  }
  return {
    launchedFile: FileItemDtoFromJSON(json['launchedFile']),
    message: json['message'],
    isCompatible: json['isCompatible'],
  };
}

export function LaunchRandomResponseToJSON(json: any): LaunchRandomResponse {
  return LaunchRandomResponseToJSONTyped(json, false);
}

export function LaunchRandomResponseToJSONTyped(
  value?: LaunchRandomResponse | null,
  ignoreDiscriminator: boolean = false
): any {
  if (value == null) {
    return value;
  }

  return {
    launchedFile: FileItemDtoToJSON(value['launchedFile']),
    message: value['message'],
    isCompatible: value['isCompatible'],
  };
}
