/* tslint:disable */
/* eslint-disable */
/**
 * TeensyRom.Api | v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 *
 * @export
 * @interface LaunchFileResponse
 */
export interface LaunchFileResponse {
  /**
   *
   * @type {string}
   * @memberof LaunchFileResponse
   */
  message: string;
}

/**
 * Check if a given object implements the LaunchFileResponse interface.
 */
export function instanceOfLaunchFileResponse(value: object): value is LaunchFileResponse {
  if (!('message' in value) || value['message'] === undefined) return false;
  return true;
}

export function LaunchFileResponseFromJSON(json: any): LaunchFileResponse {
  return LaunchFileResponseFromJSONTyped(json, false);
}

export function LaunchFileResponseFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): LaunchFileResponse {
  if (json == null) {
    return json;
  }
  return {
    message: json['message'],
  };
}

export function LaunchFileResponseToJSON(json: any): LaunchFileResponse {
  return LaunchFileResponseToJSONTyped(json, false);
}

export function LaunchFileResponseToJSONTyped(
  value?: LaunchFileResponse | null,
  ignoreDiscriminator: boolean = false
): any {
  if (value == null) {
    return value;
  }

  return {
    message: value['message'],
  };
}
