/* tslint:disable */
/* eslint-disable */
/**
 * TeensyRom.Api | v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { FileItemDto } from './FileItemDto';
import {
    FileItemDtoFromJSON,
    FileItemDtoFromJSONTyped,
    FileItemDtoToJSON,
    FileItemDtoToJSONTyped,
} from './FileItemDto';

/**
 * 
 * @export
 * @interface LaunchFileResponse
 */
export interface LaunchFileResponse {
    /**
     * 
     * @type {string}
     * @memberof LaunchFileResponse
     */
    message: string;
    /**
     * 
     * @type {FileItemDto}
     * @memberof LaunchFileResponse
     */
    launchedFile: FileItemDto;
    /**
     * 
     * @type {boolean}
     * @memberof LaunchFileResponse
     */
    isCompatible: boolean;
}

/**
 * Check if a given object implements the LaunchFileResponse interface.
 */
export function instanceOfLaunchFileResponse(value: object): value is LaunchFileResponse {
    if (!('message' in value) || value['message'] === undefined) return false;
    if (!('launchedFile' in value) || value['launchedFile'] === undefined) return false;
    if (!('isCompatible' in value) || value['isCompatible'] === undefined) return false;
    return true;
}

export function LaunchFileResponseFromJSON(json: any): LaunchFileResponse {
    return LaunchFileResponseFromJSONTyped(json, false);
}

export function LaunchFileResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): LaunchFileResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'message': json['message'],
        'launchedFile': FileItemDtoFromJSON(json['launchedFile']),
        'isCompatible': json['isCompatible'],
    };
}

export function LaunchFileResponseToJSON(json: any): LaunchFileResponse {
    return LaunchFileResponseToJSONTyped(json, false);
}

export function LaunchFileResponseToJSONTyped(value?: LaunchFileResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'message': value['message'],
        'launchedFile': FileItemDtoToJSON(value['launchedFile']),
        'isCompatible': value['isCompatible'],
    };
}

