/* tslint:disable */
/* eslint-disable */
/**
 * TeensyRom.Api | v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const NullableOfTeensyFilterType = {
    All: 'All',
    Games: 'Games',
    Music: 'Music',
    Hex: 'Hex',
    Images: 'Images'
} as const;
export type NullableOfTeensyFilterType = typeof NullableOfTeensyFilterType[keyof typeof NullableOfTeensyFilterType];


export function instanceOfNullableOfTeensyFilterType(value: any): boolean {
    for (const key in NullableOfTeensyFilterType) {
        if (Object.prototype.hasOwnProperty.call(NullableOfTeensyFilterType, key)) {
            if (NullableOfTeensyFilterType[key as keyof typeof NullableOfTeensyFilterType] === value) {
                return true;
            }
        }
    }
    return false;
}

export function NullableOfTeensyFilterTypeFromJSON(json: any): NullableOfTeensyFilterType {
    return NullableOfTeensyFilterTypeFromJSONTyped(json, false);
}

export function NullableOfTeensyFilterTypeFromJSONTyped(json: any, ignoreDiscriminator: boolean): NullableOfTeensyFilterType {
    return json as NullableOfTeensyFilterType;
}

export function NullableOfTeensyFilterTypeToJSON(value?: NullableOfTeensyFilterType | null): any {
    return value as any;
}

export function NullableOfTeensyFilterTypeToJSONTyped(value: any, ignoreDiscriminator: boolean): NullableOfTeensyFilterType {
    return value as NullableOfTeensyFilterType;
}

