/* tslint:disable */
/* eslint-disable */
/**
 * TeensyRom.Api | v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PingDeviceResponse
 */
export interface PingDeviceResponse {
    /**
     * 
     * @type {string}
     * @memberof PingDeviceResponse
     */
    message: string;
}

/**
 * Check if a given object implements the PingDeviceResponse interface.
 */
export function instanceOfPingDeviceResponse(value: object): value is PingDeviceResponse {
    if (!('message' in value) || value['message'] === undefined) return false;
    return true;
}

export function PingDeviceResponseFromJSON(json: any): PingDeviceResponse {
    return PingDeviceResponseFromJSONTyped(json, false);
}

export function PingDeviceResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): PingDeviceResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'message': json['message'],
    };
}

export function PingDeviceResponseToJSON(json: any): PingDeviceResponse {
    return PingDeviceResponseToJSONTyped(json, false);
}

export function PingDeviceResponseToJSONTyped(value?: PingDeviceResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'message': value['message'],
    };
}

