/* tslint:disable */
/* eslint-disable */
/**
 * TeensyRom.Api | v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 *
 * @export
 * @interface RemoveFavoriteResponse
 */
export interface RemoveFavoriteResponse {
  /**
   *
   * @type {string}
   * @memberof RemoveFavoriteResponse
   */
  message: string;
}

/**
 * Check if a given object implements the RemoveFavoriteResponse interface.
 */
export function instanceOfRemoveFavoriteResponse(value: object): value is RemoveFavoriteResponse {
  if (!('message' in value) || value['message'] === undefined) return false;
  return true;
}

export function RemoveFavoriteResponseFromJSON(json: any): RemoveFavoriteResponse {
  return RemoveFavoriteResponseFromJSONTyped(json, false);
}

export function RemoveFavoriteResponseFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): RemoveFavoriteResponse {
  if (json == null) {
    return json;
  }
  return {
    message: json['message'],
  };
}

export function RemoveFavoriteResponseToJSON(json: any): RemoveFavoriteResponse {
  return RemoveFavoriteResponseToJSONTyped(json, false);
}

export function RemoveFavoriteResponseToJSONTyped(
  value?: RemoveFavoriteResponse | null,
  ignoreDiscriminator: boolean = false
): any {
  if (value == null) {
    return value;
  }

  return {
    message: value['message'],
  };
}
