/* tslint:disable */
/* eslint-disable */
/**
 * TeensyRom.Api | v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ResetDeviceResponse
 */
export interface ResetDeviceResponse {
    /**
     * 
     * @type {string}
     * @memberof ResetDeviceResponse
     */
    message: string;
}

/**
 * Check if a given object implements the ResetDeviceResponse interface.
 */
export function instanceOfResetDeviceResponse(value: object): value is ResetDeviceResponse {
    if (!('message' in value) || value['message'] === undefined) return false;
    return true;
}

export function ResetDeviceResponseFromJSON(json: any): ResetDeviceResponse {
    return ResetDeviceResponseFromJSONTyped(json, false);
}

export function ResetDeviceResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ResetDeviceResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'message': json['message'],
    };
}

export function ResetDeviceResponseToJSON(json: any): ResetDeviceResponse {
    return ResetDeviceResponseToJSONTyped(json, false);
}

export function ResetDeviceResponseToJSONTyped(value?: ResetDeviceResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'message': value['message'],
    };
}

