/* tslint:disable */
/* eslint-disable */
/**
 * TeensyRom.Api | v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { FileItemDto } from './FileItemDto';
import {
    FileItemDtoFromJSON,
    FileItemDtoFromJSONTyped,
    FileItemDtoToJSON,
    FileItemDtoToJSONTyped,
} from './FileItemDto';

/**
 * 
 * @export
 * @interface SaveFavoriteResponse
 */
export interface SaveFavoriteResponse {
    /**
     * 
     * @type {string}
     * @memberof SaveFavoriteResponse
     */
    message: string;
    /**
     * 
     * @type {FileItemDto}
     * @memberof SaveFavoriteResponse
     */
    favoriteFile: FileItemDto;
    /**
     * 
     * @type {string}
     * @memberof SaveFavoriteResponse
     */
    favoritePath: string;
}

/**
 * Check if a given object implements the SaveFavoriteResponse interface.
 */
export function instanceOfSaveFavoriteResponse(value: object): value is SaveFavoriteResponse {
    if (!('message' in value) || value['message'] === undefined) return false;
    if (!('favoriteFile' in value) || value['favoriteFile'] === undefined) return false;
    if (!('favoritePath' in value) || value['favoritePath'] === undefined) return false;
    return true;
}

export function SaveFavoriteResponseFromJSON(json: any): SaveFavoriteResponse {
    return SaveFavoriteResponseFromJSONTyped(json, false);
}

export function SaveFavoriteResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): SaveFavoriteResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'message': json['message'],
        'favoriteFile': FileItemDtoFromJSON(json['favoriteFile']),
        'favoritePath': json['favoritePath'],
    };
}

export function SaveFavoriteResponseToJSON(json: any): SaveFavoriteResponse {
    return SaveFavoriteResponseToJSONTyped(json, false);
}

export function SaveFavoriteResponseToJSONTyped(value?: SaveFavoriteResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'message': value['message'],
        'favoriteFile': FileItemDtoToJSON(value['favoriteFile']),
        'favoritePath': value['favoritePath'],
    };
}

