/* tslint:disable */
/* eslint-disable */
/**
 * TeensyRom.Api | v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { FileItemDto } from './FileItemDto';
import {
  FileItemDtoFromJSON,
  FileItemDtoFromJSONTyped,
  FileItemDtoToJSON,
  FileItemDtoToJSONTyped,
} from './FileItemDto';

/**
 *
 * @export
 * @interface SearchResponse
 */
export interface SearchResponse {
  /**
   *
   * @type {Array<FileItemDto>}
   * @memberof SearchResponse
   */
  files: Array<FileItemDto>;
  /**
   *
   * @type {string}
   * @memberof SearchResponse
   */
  searchText: string;
  /**
   *
   * @type {number}
   * @memberof SearchResponse
   */
  totalCount: number;
  /**
   *
   * @type {number}
   * @memberof SearchResponse
   */
  count: number;
  /**
   *
   * @type {number}
   * @memberof SearchResponse
   */
  skip: number;
  /**
   *
   * @type {number}
   * @memberof SearchResponse
   */
  take: number;
  /**
   *
   * @type {boolean}
   * @memberof SearchResponse
   */
  hasMore: boolean;
  /**
   *
   * @type {string}
   * @memberof SearchResponse
   */
  message: string;
}

/**
 * Check if a given object implements the SearchResponse interface.
 */
export function instanceOfSearchResponse(value: object): value is SearchResponse {
  if (!('files' in value) || value['files'] === undefined) return false;
  if (!('searchText' in value) || value['searchText'] === undefined) return false;
  if (!('totalCount' in value) || value['totalCount'] === undefined) return false;
  if (!('count' in value) || value['count'] === undefined) return false;
  if (!('skip' in value) || value['skip'] === undefined) return false;
  if (!('take' in value) || value['take'] === undefined) return false;
  if (!('hasMore' in value) || value['hasMore'] === undefined) return false;
  if (!('message' in value) || value['message'] === undefined) return false;
  return true;
}

export function SearchResponseFromJSON(json: any): SearchResponse {
  return SearchResponseFromJSONTyped(json, false);
}

export function SearchResponseFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): SearchResponse {
  if (json == null) {
    return json;
  }
  return {
    files: (json['files'] as Array<any>).map(FileItemDtoFromJSON),
    searchText: json['searchText'],
    totalCount: json['totalCount'],
    count: json['count'],
    skip: json['skip'],
    take: json['take'],
    hasMore: json['hasMore'],
    message: json['message'],
  };
}

export function SearchResponseToJSON(json: any): SearchResponse {
  return SearchResponseToJSONTyped(json, false);
}

export function SearchResponseToJSONTyped(
  value?: SearchResponse | null,
  ignoreDiscriminator: boolean = false
): any {
  if (value == null) {
    return value;
  }

  return {
    files: (value['files'] as Array<any>).map(FileItemDtoToJSON),
    searchText: value['searchText'],
    totalCount: value['totalCount'],
    count: value['count'],
    skip: value['skip'],
    take: value['take'],
    hasMore: value['hasMore'],
    message: value['message'],
  };
}
