/* tslint:disable */
/* eslint-disable */
/**
 * TeensyRom.Api | v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 *
 * @export
 * @interface StartLogsResponse
 */
export interface StartLogsResponse {
  /**
   *
   * @type {string}
   * @memberof StartLogsResponse
   */
  message?: string;
}

/**
 * Check if a given object implements the StartLogsResponse interface.
 */
export function instanceOfStartLogsResponse(value: object): value is StartLogsResponse {
  return true;
}

export function StartLogsResponseFromJSON(json: any): StartLogsResponse {
  return StartLogsResponseFromJSONTyped(json, false);
}

export function StartLogsResponseFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): StartLogsResponse {
  if (json == null) {
    return json;
  }
  return {
    message: json['message'] == null ? undefined : json['message'],
  };
}

export function StartLogsResponseToJSON(json: any): StartLogsResponse {
  return StartLogsResponseToJSONTyped(json, false);
}

export function StartLogsResponseToJSONTyped(
  value?: StartLogsResponse | null,
  ignoreDiscriminator: boolean = false
): any {
  if (value == null) {
    return value;
  }

  return {
    message: value['message'],
  };
}
