/* tslint:disable */
/* eslint-disable */
/**
 * TeensyRom.Api | v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface StopLogsResponse
 */
export interface StopLogsResponse {
    /**
     * 
     * @type {string}
     * @memberof StopLogsResponse
     */
    message?: string;
}

/**
 * Check if a given object implements the StopLogsResponse interface.
 */
export function instanceOfStopLogsResponse(value: object): value is StopLogsResponse {
    return true;
}

export function StopLogsResponseFromJSON(json: any): StopLogsResponse {
    return StopLogsResponseFromJSONTyped(json, false);
}

export function StopLogsResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): StopLogsResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'message': json['message'] == null ? undefined : json['message'],
    };
}

export function StopLogsResponseToJSON(json: any): StopLogsResponse {
    return StopLogsResponseToJSONTyped(json, false);
}

export function StopLogsResponseToJSONTyped(value?: StopLogsResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'message': value['message'],
    };
}

