/* tslint:disable */
/* eslint-disable */
/**
 * TeensyRom.Api | v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { FileItemDto } from './FileItemDto';
import {
    FileItemDtoFromJSON,
    FileItemDtoFromJSONTyped,
    FileItemDtoToJSON,
    FileItemDtoToJSONTyped,
} from './FileItemDto';
import type { DirectoryItemDto } from './DirectoryItemDto';
import {
    DirectoryItemDtoFromJSON,
    DirectoryItemDtoFromJSONTyped,
    DirectoryItemDtoToJSON,
    DirectoryItemDtoToJSONTyped,
} from './DirectoryItemDto';

/**
 * 
 * @export
 * @interface StorageCacheDto
 */
export interface StorageCacheDto {
    /**
     * 
     * @type {Array<DirectoryItemDto>}
     * @memberof StorageCacheDto
     */
    directories: Array<DirectoryItemDto>;
    /**
     * 
     * @type {Array<FileItemDto>}
     * @memberof StorageCacheDto
     */
    files: Array<FileItemDto>;
    /**
     * 
     * @type {string}
     * @memberof StorageCacheDto
     */
    path: string;
}

/**
 * Check if a given object implements the StorageCacheDto interface.
 */
export function instanceOfStorageCacheDto(value: object): value is StorageCacheDto {
    if (!('directories' in value) || value['directories'] === undefined) return false;
    if (!('files' in value) || value['files'] === undefined) return false;
    if (!('path' in value) || value['path'] === undefined) return false;
    return true;
}

export function StorageCacheDtoFromJSON(json: any): StorageCacheDto {
    return StorageCacheDtoFromJSONTyped(json, false);
}

export function StorageCacheDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): StorageCacheDto {
    if (json == null) {
        return json;
    }
    return {
        
        'directories': ((json['directories'] as Array<any>).map(DirectoryItemDtoFromJSON)),
        'files': ((json['files'] as Array<any>).map(FileItemDtoFromJSON)),
        'path': json['path'],
    };
}

export function StorageCacheDtoToJSON(json: any): StorageCacheDto {
    return StorageCacheDtoToJSONTyped(json, false);
}

export function StorageCacheDtoToJSONTyped(value?: StorageCacheDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'directories': ((value['directories'] as Array<any>).map(DirectoryItemDtoToJSON)),
        'files': ((value['files'] as Array<any>).map(FileItemDtoToJSON)),
        'path': value['path'],
    };
}

