/* tslint:disable */
/* eslint-disable */
/**
 * TeensyRom.Api | v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const TeensyStorageType = {
    Sd: 'SD',
    Usb: 'USB'
} as const;
export type TeensyStorageType = typeof TeensyStorageType[keyof typeof TeensyStorageType];


export function instanceOfTeensyStorageType(value: any): boolean {
    for (const key in TeensyStorageType) {
        if (Object.prototype.hasOwnProperty.call(TeensyStorageType, key)) {
            if (TeensyStorageType[key as keyof typeof TeensyStorageType] === value) {
                return true;
            }
        }
    }
    return false;
}

export function TeensyStorageTypeFromJSON(json: any): TeensyStorageType {
    return TeensyStorageTypeFromJSONTyped(json, false);
}

export function TeensyStorageTypeFromJSONTyped(json: any, ignoreDiscriminator: boolean): TeensyStorageType {
    return json as TeensyStorageType;
}

export function TeensyStorageTypeToJSON(value?: TeensyStorageType | null): any {
    return value as any;
}

export function TeensyStorageTypeToJSONTyped(value: any, ignoreDiscriminator: boolean): TeensyStorageType {
    return value as TeensyStorageType;
}

