/* tslint:disable */
/* eslint-disable */
/**
 * TeensyRom.Api | v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ToggleMusicResponse
 */
export interface ToggleMusicResponse {
    /**
     * 
     * @type {string}
     * @memberof ToggleMusicResponse
     */
    message: string;
}

/**
 * Check if a given object implements the ToggleMusicResponse interface.
 */
export function instanceOfToggleMusicResponse(value: object): value is ToggleMusicResponse {
    if (!('message' in value) || value['message'] === undefined) return false;
    return true;
}

export function ToggleMusicResponseFromJSON(json: any): ToggleMusicResponse {
    return ToggleMusicResponseFromJSONTyped(json, false);
}

export function ToggleMusicResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ToggleMusicResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'message': json['message'],
    };
}

export function ToggleMusicResponseToJSON(json: any): ToggleMusicResponse {
    return ToggleMusicResponseToJSONTyped(json, false);
}

export function ToggleMusicResponseToJSONTyped(value?: ToggleMusicResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'message': value['message'],
    };
}

