/* tslint:disable */
/* eslint-disable */
/**
 * TeensyRom.Api | v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ViewableItemImageDto
 */
export interface ViewableItemImageDto {
    /**
     * 
     * @type {string}
     * @memberof ViewableItemImageDto
     */
    fileName: string;
    /**
     * 
     * @type {string}
     * @memberof ViewableItemImageDto
     */
    path: string;
    /**
     * 
     * @type {string}
     * @memberof ViewableItemImageDto
     */
    source: string;
}

/**
 * Check if a given object implements the ViewableItemImageDto interface.
 */
export function instanceOfViewableItemImageDto(value: object): value is ViewableItemImageDto {
    if (!('fileName' in value) || value['fileName'] === undefined) return false;
    if (!('path' in value) || value['path'] === undefined) return false;
    if (!('source' in value) || value['source'] === undefined) return false;
    return true;
}

export function ViewableItemImageDtoFromJSON(json: any): ViewableItemImageDto {
    return ViewableItemImageDtoFromJSONTyped(json, false);
}

export function ViewableItemImageDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): ViewableItemImageDto {
    if (json == null) {
        return json;
    }
    return {
        
        'fileName': json['fileName'],
        'path': json['path'],
        'source': json['source'],
    };
}

export function ViewableItemImageDtoToJSON(json: any): ViewableItemImageDto {
    return ViewableItemImageDtoToJSONTyped(json, false);
}

export function ViewableItemImageDtoToJSONTyped(value?: ViewableItemImageDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'fileName': value['fileName'],
        'path': value['path'],
        'source': value['source'],
    };
}

