/* tslint:disable */
/* eslint-disable */
/**
 * TeensyRom.Api | v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface YouTubeVideoDto
 */
export interface YouTubeVideoDto {
    /**
     * 
     * @type {string}
     * @memberof YouTubeVideoDto
     */
    videoId: string;
    /**
     * 
     * @type {string}
     * @memberof YouTubeVideoDto
     */
    url: string;
    /**
     * 
     * @type {string}
     * @memberof YouTubeVideoDto
     */
    channel: string;
    /**
     * 
     * @type {number}
     * @memberof YouTubeVideoDto
     */
    subtune: number;
}

/**
 * Check if a given object implements the YouTubeVideoDto interface.
 */
export function instanceOfYouTubeVideoDto(value: object): value is YouTubeVideoDto {
    if (!('videoId' in value) || value['videoId'] === undefined) return false;
    if (!('url' in value) || value['url'] === undefined) return false;
    if (!('channel' in value) || value['channel'] === undefined) return false;
    if (!('subtune' in value) || value['subtune'] === undefined) return false;
    return true;
}

export function YouTubeVideoDtoFromJSON(json: any): YouTubeVideoDto {
    return YouTubeVideoDtoFromJSONTyped(json, false);
}

export function YouTubeVideoDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): YouTubeVideoDto {
    if (json == null) {
        return json;
    }
    return {
        
        'videoId': json['videoId'],
        'url': json['url'],
        'channel': json['channel'],
        'subtune': json['subtune'],
    };
}

export function YouTubeVideoDtoToJSON(json: any): YouTubeVideoDto {
    return YouTubeVideoDtoToJSONTyped(json, false);
}

export function YouTubeVideoDtoToJSONTyped(value?: YouTubeVideoDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'videoId': value['videoId'],
        'url': value['url'],
        'channel': value['channel'],
        'subtune': value['subtune'],
    };
}

