/**
 * TeensyRom.Api
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { ConnectDeviceResponse } from '../model/models';
import { DisconnectDeviceResponse } from '../model/models';
import { FindDevicesResponse } from '../model/models';
import { ProblemDetails } from '../model/models';
import { ResetDeviceResponse } from '../model/models';


import { Configuration }                                     from '../configuration';


export interface DevicesDeviceIdConnectPostRequestParams {
    deviceId: string;
}

export interface DevicesDeviceIdDeleteRequestParams {
    deviceId: string;
}

export interface DevicesDeviceIdResetPutRequestParams {
    deviceId: string;
}


export interface DevicesServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * 
     * Connects to a TeensyRom device given an ID.
* @param requestParameters
     */
    devicesDeviceIdConnectPost(requestParameters: DevicesDeviceIdConnectPostRequestParams, extraHttpRequestParams?: any): Observable<ConnectDeviceResponse>;

    /**
     * 
     * Close device port.
* @param requestParameters
     */
    devicesDeviceIdDelete(requestParameters: DevicesDeviceIdDeleteRequestParams, extraHttpRequestParams?: any): Observable<DisconnectDeviceResponse>;

    /**
     * 
     * Resets the given device matching the give device id.
* @param requestParameters
     */
    devicesDeviceIdResetPut(requestParameters: DevicesDeviceIdResetPutRequestParams, extraHttpRequestParams?: any): Observable<ResetDeviceResponse>;

    /**
     * 
     * Returns all available and connected TeensyROM devices.
*/
    devicesGet(extraHttpRequestParams?: any): Observable<FindDevicesResponse>;

}
