/* tslint:disable */
/* eslint-disable */
/**
 * TeensyRom.Api | v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import type {
  ConnectDeviceResponse,
  DeviceStartResponse,
  DeviceStopResponse,
  DisconnectDeviceResponse,
  FindDevicesResponse,
  PingDeviceResponse,
  ProblemDetails,
  ResetDeviceResponse,
  StartLogsResponse,
  StopLogsResponse,
} from '../models/index';
import {
  ConnectDeviceResponseFromJSON,
  ConnectDeviceResponseToJSON,
  DeviceStartResponseFromJSON,
  DeviceStartResponseToJSON,
  DeviceStopResponseFromJSON,
  DeviceStopResponseToJSON,
  DisconnectDeviceResponseFromJSON,
  DisconnectDeviceResponseToJSON,
  FindDevicesResponseFromJSON,
  FindDevicesResponseToJSON,
  PingDeviceResponseFromJSON,
  PingDeviceResponseToJSON,
  ProblemDetailsFromJSON,
  ProblemDetailsToJSON,
  ResetDeviceResponseFromJSON,
  ResetDeviceResponseToJSON,
  StartLogsResponseFromJSON,
  StartLogsResponseToJSON,
  StopLogsResponseFromJSON,
  StopLogsResponseToJSON,
} from '../models/index';

export interface ConnectDeviceRequest {
  deviceId: string;
}

export interface DisconnectDeviceRequest {
  deviceId: string;
}

export interface FindDevicesRequest {
  autoConnectNew?: boolean;
}

export interface PingDeviceRequest {
  deviceId: string;
}

export interface ResetDeviceRequest {
  deviceId: string;
}

/**
 *
 */
export class DevicesApiService extends runtime.BaseAPI {
  /**
   * Connects to a TeensyROM device.  - You must be connected to a TeensyROM device in order to call most other endpoints.
   * Connect Device
   */
  async connectDeviceRaw(
    requestParameters: ConnectDeviceRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<runtime.ApiResponse<ConnectDeviceResponse>> {
    if (requestParameters['deviceId'] == null) {
      throw new runtime.RequiredError(
        'deviceId',
        'Required parameter "deviceId" was null or undefined when calling connectDevice().'
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    const response = await this.request(
      {
        path: `/devices/{deviceId}/connect`.replace(
          `{${'deviceId'}}`,
          encodeURIComponent(String(requestParameters['deviceId']))
        ),
        method: 'POST',
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides
    );

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      ConnectDeviceResponseFromJSON(jsonValue)
    );
  }

  /**
   * Connects to a TeensyROM device.  - You must be connected to a TeensyROM device in order to call most other endpoints.
   * Connect Device
   */
  async connectDevice(
    requestParameters: ConnectDeviceRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<ConnectDeviceResponse> {
    const response = await this.connectDeviceRaw(requestParameters, initOverrides);
    return await response.value();
  }

  /**
   * Disconnnects from a TeensyROM device.  - Once you disconnect from a device, most endpoints won\'t work until you reconnect.
   * Disconnect Device
   */
  async disconnectDeviceRaw(
    requestParameters: DisconnectDeviceRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<runtime.ApiResponse<DisconnectDeviceResponse>> {
    if (requestParameters['deviceId'] == null) {
      throw new runtime.RequiredError(
        'deviceId',
        'Required parameter "deviceId" was null or undefined when calling disconnectDevice().'
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    const response = await this.request(
      {
        path: `/devices/{deviceId}`.replace(
          `{${'deviceId'}}`,
          encodeURIComponent(String(requestParameters['deviceId']))
        ),
        method: 'DELETE',
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides
    );

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      DisconnectDeviceResponseFromJSON(jsonValue)
    );
  }

  /**
   * Disconnnects from a TeensyROM device.  - Once you disconnect from a device, most endpoints won\'t work until you reconnect.
   * Disconnect Device
   */
  async disconnectDevice(
    requestParameters: DisconnectDeviceRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<DisconnectDeviceResponse> {
    const response = await this.disconnectDeviceRaw(requestParameters, initOverrides);
    return await response.value();
  }

  /**
   * Returns all available and connected TeensyROM devices.  - This will momentarily disconnect all devices. - All available COM ports will be scanned for TeensyROM devices. - All previously connected devices will reconnect.
   * Find Devices
   */
  async findDevicesRaw(
    requestParameters: FindDevicesRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<runtime.ApiResponse<FindDevicesResponse>> {
    const queryParameters: any = {};

    if (requestParameters['autoConnectNew'] != null) {
      queryParameters['AutoConnectNew'] = requestParameters['autoConnectNew'];
    }

    const headerParameters: runtime.HTTPHeaders = {};

    const response = await this.request(
      {
        path: `/devices`,
        method: 'GET',
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides
    );

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      FindDevicesResponseFromJSON(jsonValue)
    );
  }

  /**
   * Returns all available and connected TeensyROM devices.  - This will momentarily disconnect all devices. - All available COM ports will be scanned for TeensyROM devices. - All previously connected devices will reconnect.
   * Find Devices
   */
  async findDevices(
    requestParameters: FindDevicesRequest = {},
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<FindDevicesResponse> {
    const response = await this.findDevicesRaw(requestParameters, initOverrides);
    return await response.value();
  }

  /**
   * Pings a TeensyROM device to check if it is responsive.  - Works the same as clicking the cartridge reset button.
   * Ping Device
   */
  async pingDeviceRaw(
    requestParameters: PingDeviceRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<runtime.ApiResponse<PingDeviceResponse>> {
    if (requestParameters['deviceId'] == null) {
      throw new runtime.RequiredError(
        'deviceId',
        'Required parameter "deviceId" was null or undefined when calling pingDevice().'
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    const response = await this.request(
      {
        path: `/devices/{deviceId}/ping`.replace(
          `{${'deviceId'}}`,
          encodeURIComponent(String(requestParameters['deviceId']))
        ),
        method: 'GET',
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides
    );

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      PingDeviceResponseFromJSON(jsonValue)
    );
  }

  /**
   * Pings a TeensyROM device to check if it is responsive.  - Works the same as clicking the cartridge reset button.
   * Ping Device
   */
  async pingDevice(
    requestParameters: PingDeviceRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<PingDeviceResponse> {
    const response = await this.pingDeviceRaw(requestParameters, initOverrides);
    return await response.value();
  }

  /**
   * Resets a TeensyROM device.  - Works the same as clicking the cartridge reset button.
   * Reset Device
   */
  async resetDeviceRaw(
    requestParameters: ResetDeviceRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<runtime.ApiResponse<ResetDeviceResponse>> {
    if (requestParameters['deviceId'] == null) {
      throw new runtime.RequiredError(
        'deviceId',
        'Required parameter "deviceId" was null or undefined when calling resetDevice().'
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    const response = await this.request(
      {
        path: `/devices/{deviceId}/reset`.replace(
          `{${'deviceId'}}`,
          encodeURIComponent(String(requestParameters['deviceId']))
        ),
        method: 'PUT',
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides
    );

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      ResetDeviceResponseFromJSON(jsonValue)
    );
  }

  /**
   * Resets a TeensyROM device.  - Works the same as clicking the cartridge reset button.
   * Reset Device
   */
  async resetDevice(
    requestParameters: ResetDeviceRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<ResetDeviceResponse> {
    const response = await this.resetDeviceRaw(requestParameters, initOverrides);
    return await response.value();
  }

  /**
   * Starts the device event stream.
   * Start Device Event Stream
   */
  async startDeviceEventsRaw(
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<runtime.ApiResponse<DeviceStartResponse>> {
    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    const response = await this.request(
      {
        path: `/devices/events`,
        method: 'GET',
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides
    );

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      DeviceStartResponseFromJSON(jsonValue)
    );
  }

  /**
   * Starts the device event stream.
   * Start Device Event Stream
   */
  async startDeviceEvents(
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<DeviceStartResponse> {
    const response = await this.startDeviceEventsRaw(initOverrides);
    return await response.value();
  }

  /**
   * Starts the logging service and returns a success message.
   * Start Logging Hub
   */
  async startLogsRaw(
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<runtime.ApiResponse<StartLogsResponse>> {
    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    const response = await this.request(
      {
        path: `/logs`,
        method: 'POST',
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides
    );

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      StartLogsResponseFromJSON(jsonValue)
    );
  }

  /**
   * Starts the logging service and returns a success message.
   * Start Logging Hub
   */
  async startLogs(
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<StartLogsResponse> {
    const response = await this.startLogsRaw(initOverrides);
    return await response.value();
  }

  /**
   * Stops the device event stream.
   * Stop Device Event Stream
   */
  async stopDeviceEventsRaw(
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<runtime.ApiResponse<DeviceStopResponse>> {
    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    const response = await this.request(
      {
        path: `/devices/events`,
        method: 'DELETE',
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides
    );

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      DeviceStopResponseFromJSON(jsonValue)
    );
  }

  /**
   * Stops the device event stream.
   * Stop Device Event Stream
   */
  async stopDeviceEvents(
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<DeviceStopResponse> {
    const response = await this.stopDeviceEventsRaw(initOverrides);
    return await response.value();
  }

  /**
   * Stops the logging service and returns a success message.
   * Stop Logging Channel
   */
  async stopLogsRaw(
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<runtime.ApiResponse<StopLogsResponse>> {
    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    const response = await this.request(
      {
        path: `/logs`,
        method: 'DELETE',
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides
    );

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      StopLogsResponseFromJSON(jsonValue)
    );
  }

  /**
   * Stops the logging service and returns a success message.
   * Stop Logging Channel
   */
  async stopLogs(
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<StopLogsResponse> {
    const response = await this.stopLogsRaw(initOverrides);
    return await response.value();
  }
}
