/* tslint:disable */
/* eslint-disable */
/**
 * TeensyRom.Api | v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  GetDirectoryResponse,
  IndexAllResponse,
  IndexResponse,
  NullableOfTeensyFilterType,
  ProblemDetails,
  SearchResponse,
  TeensyStorageType,
} from '../models/index';
import {
    GetDirectoryResponseFromJSON,
    GetDirectoryResponseToJSON,
    IndexAllResponseFromJSON,
    IndexAllResponseToJSON,
    IndexResponseFromJSON,
    IndexResponseToJSON,
    NullableOfTeensyFilterTypeFromJSON,
    NullableOfTeensyFilterTypeToJSON,
    ProblemDetailsFromJSON,
    ProblemDetailsToJSON,
    SearchResponseFromJSON,
    SearchResponseToJSON,
    TeensyStorageTypeFromJSON,
    TeensyStorageTypeToJSON,
} from '../models/index';

export interface GetDirectoryRequest {
    deviceId: string;
    storageType: TeensyStorageType;
    path?: string;
}

export interface IndexRequest {
    deviceId: string;
    storageType: TeensyStorageType;
    startingPath?: string;
}

export interface SearchRequest {
    deviceId: string;
    storageType: TeensyStorageType;
    searchText: string;
    filterType?: NullableOfTeensyFilterType;
}

/**
 * 
 */
export class FilesApiService extends runtime.BaseAPI {

    /**
     * Gets a directory for given storage device.  - Returns metadata for all files in the directory. - This is not recursive and will only include the files for the requested directory. - Make another request to get subdirectory content.
     * Get Directory
     */
    async getDirectoryRaw(requestParameters: GetDirectoryRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<GetDirectoryResponse>> {
        if (requestParameters['deviceId'] == null) {
            throw new runtime.RequiredError(
                'deviceId',
                'Required parameter "deviceId" was null or undefined when calling getDirectory().'
            );
        }

        if (requestParameters['storageType'] == null) {
            throw new runtime.RequiredError(
                'storageType',
                'Required parameter "storageType" was null or undefined when calling getDirectory().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['path'] != null) {
            queryParameters['Path'] = requestParameters['path'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/devices/{deviceId}/storage/{storageType}/directories`.replace(`{${"deviceId"}}`, encodeURIComponent(String(requestParameters['deviceId']))).replace(`{${"storageType"}}`, encodeURIComponent(String(requestParameters['storageType']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => GetDirectoryResponseFromJSON(jsonValue));
    }

    /**
     * Gets a directory for given storage device.  - Returns metadata for all files in the directory. - This is not recursive and will only include the files for the requested directory. - Make another request to get subdirectory content.
     * Get Directory
     */
    async getDirectory(requestParameters: GetDirectoryRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<GetDirectoryResponse> {
        const response = await this.getDirectoryRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Indexes the directory structure of a given TeensyROM device and storage type.  - Providing a path will index starting at that directory and all subdirectories below it. - Providing no path will index the whole storage device. - Don\'t touch your commodore while indexing is in progress.
     * Index
     */
    async indexRaw(requestParameters: IndexRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<IndexResponse>> {
        if (requestParameters['deviceId'] == null) {
            throw new runtime.RequiredError(
                'deviceId',
                'Required parameter "deviceId" was null or undefined when calling index().'
            );
        }

        if (requestParameters['storageType'] == null) {
            throw new runtime.RequiredError(
                'storageType',
                'Required parameter "storageType" was null or undefined when calling index().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['startingPath'] != null) {
            queryParameters['StartingPath'] = requestParameters['startingPath'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/devices/{deviceId}/storage/{storageType}/index`.replace(`{${"deviceId"}}`, encodeURIComponent(String(requestParameters['deviceId']))).replace(`{${"storageType"}}`, encodeURIComponent(String(requestParameters['storageType']))),
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => IndexResponseFromJSON(jsonValue));
    }

    /**
     * Indexes the directory structure of a given TeensyROM device and storage type.  - Providing a path will index starting at that directory and all subdirectories below it. - Providing no path will index the whole storage device. - Don\'t touch your commodore while indexing is in progress.
     * Index
     */
    async index(requestParameters: IndexRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<IndexResponse> {
        const response = await this.indexRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Indexes all storage for all connected TeensyROM devices.  - This will recursively index all storage devices. - Multiple devices will be indexed in parallel, one device type at a time. - This could take a few minutes if you have a lot of data. - Don\'t touch your commodores while indexing is in progress.
     * Index All
     */
    async indexAllRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<IndexAllResponse>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/files/index/all`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => IndexAllResponseFromJSON(jsonValue));
    }

    /**
     * Indexes all storage for all connected TeensyROM devices.  - This will recursively index all storage devices. - Multiple devices will be indexed in parallel, one device type at a time. - This could take a few minutes if you have a lot of data. - Don\'t touch your commodores while indexing is in progress.
     * Index All
     */
    async indexAll(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<IndexAllResponse> {
        const response = await this.indexAllRaw(initOverrides);
        return await response.value();
    }

    /**
     * Searches for files in the specified storage device based on search text and filter criteria.  - Searches through file names, titles, creators, and descriptions. - Returns metadata for all matching files. - Supports file type filtering (All, Games, Music, Images, Hex). - Excludes favorites and playlist directories from search results. - Uses weighted search algorithm to rank results by relevance.
     * Search Files
     */
    async searchRaw(requestParameters: SearchRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SearchResponse>> {
        if (requestParameters['deviceId'] == null) {
            throw new runtime.RequiredError(
                'deviceId',
                'Required parameter "deviceId" was null or undefined when calling search().'
            );
        }

        if (requestParameters['storageType'] == null) {
            throw new runtime.RequiredError(
                'storageType',
                'Required parameter "storageType" was null or undefined when calling search().'
            );
        }

        if (requestParameters['searchText'] == null) {
            throw new runtime.RequiredError(
                'searchText',
                'Required parameter "searchText" was null or undefined when calling search().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['searchText'] != null) {
            queryParameters['SearchText'] = requestParameters['searchText'];
        }

        if (requestParameters['filterType'] != null) {
            queryParameters['FilterType'] = requestParameters['filterType'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/devices/{deviceId}/storage/{storageType}/search`.replace(`{${"deviceId"}}`, encodeURIComponent(String(requestParameters['deviceId']))).replace(`{${"storageType"}}`, encodeURIComponent(String(requestParameters['storageType']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => SearchResponseFromJSON(jsonValue));
    }

    /**
     * Searches for files in the specified storage device based on search text and filter criteria.  - Searches through file names, titles, creators, and descriptions. - Returns metadata for all matching files. - Supports file type filtering (All, Games, Music, Images, Hex). - Excludes favorites and playlist directories from search results. - Uses weighted search algorithm to rank results by relevance.
     * Search Files
     */
    async search(requestParameters: SearchRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SearchResponse> {
        const response = await this.searchRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
