/* tslint:disable */
/* eslint-disable */
/**
 * TeensyRom.Api | v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import type {
  LaunchFileResponse,
  LaunchRandomResponse,
  ProblemDetails,
  TeensyStorageType,
} from '../models/index';
import {
  LaunchFileResponseFromJSON,
  LaunchFileResponseToJSON,
  LaunchRandomResponseFromJSON,
  LaunchRandomResponseToJSON,
  ProblemDetailsFromJSON,
  ProblemDetailsToJSON,
  TeensyStorageTypeFromJSON,
  TeensyStorageTypeToJSON,
} from '../models/index';

export interface LaunchFileRequest {
  deviceId: string;
  storageType: TeensyStorageType;
  filePath: string;
}

export interface LaunchRandomRequest {
  deviceId: string;
  storageType: TeensyStorageType;
  filterType?: LaunchRandomFilterTypeEnum;
  scope?: LaunchRandomScopeEnum;
  startingDirectory?: string;
}

/**
 *
 */
export class PlayerApiService extends runtime.BaseAPI {
  /**
   * Launches a file given a valid path to a file stored on the TeensyRom.
   * Launch File
   */
  async launchFileRaw(
    requestParameters: LaunchFileRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<runtime.ApiResponse<LaunchFileResponse>> {
    if (requestParameters['deviceId'] == null) {
      throw new runtime.RequiredError(
        'deviceId',
        'Required parameter "deviceId" was null or undefined when calling launchFile().'
      );
    }

    if (requestParameters['storageType'] == null) {
      throw new runtime.RequiredError(
        'storageType',
        'Required parameter "storageType" was null or undefined when calling launchFile().'
      );
    }

    if (requestParameters['filePath'] == null) {
      throw new runtime.RequiredError(
        'filePath',
        'Required parameter "filePath" was null or undefined when calling launchFile().'
      );
    }

    const queryParameters: any = {};

    if (requestParameters['filePath'] != null) {
      queryParameters['FilePath'] = requestParameters['filePath'];
    }

    const headerParameters: runtime.HTTPHeaders = {};

    const response = await this.request(
      {
        path: `/devices/{deviceId}/storage/{storageType}/launch`
          .replace(`{${'deviceId'}}`, encodeURIComponent(String(requestParameters['deviceId'])))
          .replace(
            `{${'storageType'}}`,
            encodeURIComponent(String(requestParameters['storageType']))
          ),
        method: 'POST',
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides
    );

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      LaunchFileResponseFromJSON(jsonValue)
    );
  }

  /**
   * Launches a file given a valid path to a file stored on the TeensyRom.
   * Launch File
   */
  async launchFile(
    requestParameters: LaunchFileRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<LaunchFileResponse> {
    const response = await this.launchFileRaw(requestParameters, initOverrides);
    return await response.value();
  }

  /**
   * Launches a random file given a device, storage, filter and starting directory location.  - Starting Directory: Starting directory to look for a random file. - Scope: `Storage` - Selects a random file anywhere on the specified storage device. - Scope: `DirDeep` - Selects a random file from the starting directory or any of its subdirectories. - Scope: `DirShallow` - Selects a random file from the starting directory only (subdirectories are not included). - Filter: `All` - Any file type will be randomly selected. - Filter: `Games` - Only game-related files will be selected (e.g., .prg, .crt, .d64, etc). Includes demos and non-games. - Filter: `Music` - Only music or song files will be selected (e.g., .sid, .mus, .mp3, etc). - Filter: `Images` - Only image files will be selected (e.g., .koa, .png, etc). Also includes text files (may be improved in a future release)
   * Launch Random File
   */
  async launchRandomRaw(
    requestParameters: LaunchRandomRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<runtime.ApiResponse<LaunchRandomResponse>> {
    if (requestParameters['deviceId'] == null) {
      throw new runtime.RequiredError(
        'deviceId',
        'Required parameter "deviceId" was null or undefined when calling launchRandom().'
      );
    }

    if (requestParameters['storageType'] == null) {
      throw new runtime.RequiredError(
        'storageType',
        'Required parameter "storageType" was null or undefined when calling launchRandom().'
      );
    }

    const queryParameters: any = {};

    if (requestParameters['filterType'] != null) {
      queryParameters['FilterType'] = requestParameters['filterType'];
    }

    if (requestParameters['scope'] != null) {
      queryParameters['Scope'] = requestParameters['scope'];
    }

    if (requestParameters['startingDirectory'] != null) {
      queryParameters['StartingDirectory'] = requestParameters['startingDirectory'];
    }

    const headerParameters: runtime.HTTPHeaders = {};

    const response = await this.request(
      {
        path: `/devices/{deviceId}/storage/{storageType}/random-launch`
          .replace(`{${'deviceId'}}`, encodeURIComponent(String(requestParameters['deviceId'])))
          .replace(
            `{${'storageType'}}`,
            encodeURIComponent(String(requestParameters['storageType']))
          ),
        method: 'POST',
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides
    );

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      LaunchRandomResponseFromJSON(jsonValue)
    );
  }

  /**
   * Launches a random file given a device, storage, filter and starting directory location.  - Starting Directory: Starting directory to look for a random file. - Scope: `Storage` - Selects a random file anywhere on the specified storage device. - Scope: `DirDeep` - Selects a random file from the starting directory or any of its subdirectories. - Scope: `DirShallow` - Selects a random file from the starting directory only (subdirectories are not included). - Filter: `All` - Any file type will be randomly selected. - Filter: `Games` - Only game-related files will be selected (e.g., .prg, .crt, .d64, etc). Includes demos and non-games. - Filter: `Music` - Only music or song files will be selected (e.g., .sid, .mus, .mp3, etc). - Filter: `Images` - Only image files will be selected (e.g., .koa, .png, etc). Also includes text files (may be improved in a future release)
   * Launch Random File
   */
  async launchRandom(
    requestParameters: LaunchRandomRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<LaunchRandomResponse> {
    const response = await this.launchRandomRaw(requestParameters, initOverrides);
    return await response.value();
  }
}

/**
 * @export
 */
export const LaunchRandomFilterTypeEnum = {
  All: 'All',
  Games: 'Games',
  Music: 'Music',
  Hex: 'Hex',
  Images: 'Images',
} as const;
export type LaunchRandomFilterTypeEnum =
  (typeof LaunchRandomFilterTypeEnum)[keyof typeof LaunchRandomFilterTypeEnum];
/**
 * @export
 */
export const LaunchRandomScopeEnum = {
  Storage: 'Storage',
  DirDeep: 'DirDeep',
  DirShallow: 'DirShallow',
} as const;
export type LaunchRandomScopeEnum =
  (typeof LaunchRandomScopeEnum)[keyof typeof LaunchRandomScopeEnum];
