/**
 * TeensyRom.Api | v1
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { CartStorageDto } from './cartStorageDto';


/**
 * Data transfer object representing a TeensyROM cartridge.
 */
export interface CartDto { 
    /**
     * The unique ID of the TeensyROM device.
     */
    deviceId?: string | null;
    /**
     * The COM port the device is connected to.
     */
    comPort?: string;
    /**
     * The user-friendly name of the device.
     */
    name?: string;
    /**
     * The firmware version of the device.
     */
    fwVersion?: string;
    /**
     * Indicates whether the device is compatible with the current application version.
     */
    isCompatible?: boolean;
    sdStorage?: CartStorageDto;
    usbStorage?: CartStorageDto;
}

