/**
 * TeensyRom.Api | v1
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Data transfer object representing a directory item in TeensyROM storage.
 */
export interface DirectoryItemDto { 
    /**
     * The name of the directory.
     */
    name?: string;
    /**
     * The full path to the directory.
     */
    path?: string;
}

