/**
 * TeensyRom.Api | v1
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { CartDto } from './cartDto';


/**
 * Response model for finding available and connected TeensyROM devices.
 */
export interface FindDevicesResponse { 
    /**
     * The list of TeensyROM devices that are available to connect.
     */
    availableCarts?: Array<CartDto>;
    /**
     * The list of TeensyROM devices that are currently connected.
     */
    connectedCarts?: Array<CartDto>;
    /**
     * A message indicating the result of the operation.
     */
    message?: string;
}

