/**
 * TeensyRom.Api | v1
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Response model for the result of an index all operation.
 */
export interface IndexAllResponse { 
    /**
     * A message indicating the result of the operation.
     */
    message?: string;
}

