/**
 * TeensyRom.Api | v1
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Data transfer object representing an image associated with a viewable item in TeensyROM storage.
 */
export interface ViewableItemImageDto { 
    /**
     * The file name of the image.
     */
    fileName?: string;
    /**
     * The full path to the image file.
     */
    path?: string;
    /**
     * The source or origin of the image.
     */
    source?: string;
}

