/**
 * TeensyRom.Api
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { CartStorage } from './cartStorage';


export interface Cart { 
    deviceId?: string | null;
    comPort?: string | null;
    name?: string | null;
    fwVersion?: string | null;
    isCompatible?: boolean;
    sdStorage?: CartStorage;
    usbStorage?: CartStorage;
}

