/**
 * TeensyRom.Api
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Cart } from './cart';


export interface ConnectDeviceResponse { 
    success?: boolean;
    connectedCart?: Cart;
    message?: string | null;
}

