/**
 * TeensyRom.Api
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ViewableItemImage } from './viewableItemImage';
import { FileItemType } from './fileItemType';


export interface FileItemViewModel { 
    name?: string | null;
    path?: string | null;
    size?: number;
    isFavorite?: boolean;
    title?: string | null;
    creator?: string | null;
    releaseInfo?: string | null;
    description?: string | null;
    shareUrl?: string | null;
    metadataSource?: string | null;
    meta1?: string | null;
    meta2?: string | null;
    metadataSourcePath?: string | null;
    favChildPath?: string | null;
    favParentPath?: string | null;
    playLength?: string | null;
    subtuneLengths?: Array<string> | null;
    startSubtuneNum?: number | null;
    images?: Array<ViewableItemImage> | null;
    type?: FileItemType;
}
export namespace FileItemViewModel {
}


