/**
 * TeensyRom.Api
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { StorageCacheViewModel } from './storageCacheViewModel';


export interface GetDirectoryResponse { 
    storageItem?: StorageCacheViewModel;
    message?: string | null;
}

