/**
 * TeensyRom.Api
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { FileItemViewModel } from './fileItemViewModel';
import { DirectoryItemViewModel } from './directoryItemViewModel';


export interface StorageCacheViewModel { 
    directories?: Array<DirectoryItemViewModel> | null;
    files?: Array<FileItemViewModel> | null;
    path?: string | null;
}

