/**
 * TeensyRom.Api
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ViewableItemImage { 
    fileName?: string | null;
    path?: string | null;
    source?: string | null;
}

