/**
 * TeensyRom.Api | v1
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { TeensyStorageType } from './teensyStorageType';

/**
 * Data transfer object representing storage information for a TeensyROM device.
 */
export interface CartStorageDto {
  /**
   * The unique ID of the TeensyROM device.
   */
  deviceId: string;
  type: TeensyStorageType;
  /**
   * Indicates whether the storage is available.
   */
  available: boolean;
}
export namespace CartStorageDto {}
