/**
 * TeensyRom.Api | v1
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { DeviceState } from './deviceState';
import { CartStorageDto } from './cartStorageDto';

export interface CartDto {
  deviceId: string;
  isConnected: boolean;
  deviceState: DeviceState;
  comPort: string;
  name: string;
  fwVersion: string;
  isCompatible: boolean;
  sdStorage: CartStorageDto;
  usbStorage: CartStorageDto;
}
export namespace CartDto {}
