/**
 * TeensyRom.Api | v1
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { CartDto } from './cartDto';

export interface ConnectDeviceResponse {
  connectedCart: CartDto;
  message: string;
}
