/**
 * TeensyRom.Api | v1
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { CartDto } from './cartDto';

/**
 * Response model for the result of a connect device operation.
 */
export interface ConnectDeviceResponse {
  connectedCart: CartDto;
  /**
   * A message indicating the result of the operation.
   */
  message: string;
}
