/**
 * TeensyRom.Api | v1
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export const DeviceState = {
  Connected: 'Connected',
  Connectable: 'Connectable',
  ConnectionLost: 'ConnectionLost',
  Busy: 'Busy',
  Unknown: 'Unknown',
} as const;
export type DeviceState = (typeof DeviceState)[keyof typeof DeviceState];
