/**
 * TeensyRom.Api | v1
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * The type of the file (e.g., Song, Game, Image, Hex, Unknown).
 */
export const FileItemType = {
  Unknown: 'Unknown',
  Song: 'Song',
  Game: 'Game',
  Image: 'Image',
  Hex: 'Hex',
} as const;
export type FileItemType = (typeof FileItemType)[keyof typeof FileItemType];
