/**
 * TeensyRom.Api | v1
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ViewableItemImageDto } from './viewableItemImageDto';
import { FileItemType } from './fileItemType';

export interface FileItemDto {
  name: string;
  path: string;
  size: number;
  isFavorite: boolean;
  title: string;
  creator: string;
  releaseInfo: string;
  description: string;
  shareUrl: string;
  metadataSource: string;
  meta1: string;
  meta2: string;
  metadataSourcePath: string;
  parentPath: string;
  playLength: string;
  subtuneLengths: Array<string>;
  startSubtuneNum: number;
  images: Array<ViewableItemImageDto>;
  type: FileItemType;
}
export namespace FileItemDto {}
