/**
 * TeensyRom.Api | v1
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { StorageCacheDto } from './storageCacheDto';

export interface GetDirectoryResponse {
  storageItem: StorageCacheDto;
  message: string;
}
