/**
 * TeensyRom.Api | v1
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { StorageCacheDto } from './storageCacheDto';

/**
 * Response model containing the directory metadata and its contents.
 */
export interface GetDirectoryResponse {
  storageItem: StorageCacheDto;
  /**
   * A message indicating the result of the operation.
   */
  message: string;
}
