/**
 * TeensyRom.Api | v1
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { FileItemDto } from './fileItemDto';

/**
 * Response model for the result of a launch random file operation.
 */
export interface LaunchRandomResponse {
  launchedFile: FileItemDto;
  /**
   * A message indicating the result of the operation.
   */
  message: string;
}
