/**
 * TeensyRom.Api | v1
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export const NullableOfStorageScope = {
  Storage: 'Storage',
  DirDeep: 'DirDeep',
  DirShallow: 'DirShallow',
} as const;
export type NullableOfStorageScope =
  (typeof NullableOfStorageScope)[keyof typeof NullableOfStorageScope];
