/**
 * TeensyRom.Api | v1
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export const NullableOfTeensyFilterType = {
  All: 'All',
  Games: 'Games',
  Music: 'Music',
  Hex: 'Hex',
  Images: 'Images',
} as const;
export type NullableOfTeensyFilterType =
  (typeof NullableOfTeensyFilterType)[keyof typeof NullableOfTeensyFilterType];
