/**
 * TeensyRom.Api | v1
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { FileItemDto } from './fileItemDto';
import { DirectoryItemDto } from './directoryItemDto';

export interface StorageCacheDto {
  directories: Array<DirectoryItemDto>;
  files: Array<FileItemDto>;
  path: string;
}
