/**
 * TeensyRom.Api | v1
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export const TeensyStorageType = {
  Sd: 'SD',
  Usb: 'USB',
} as const;
export type TeensyStorageType = (typeof TeensyStorageType)[keyof typeof TeensyStorageType];
