/**
 * TeensyRom.Api
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { TeensyStorageType } from './teensyStorageType';


export interface CartStorage { 
    deviceId?: string | null;
    type?: TeensyStorageType;
    available?: boolean;
}
export namespace CartStorage {
}


