/**
 * TeensyRom.Api
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Cart } from './cart';


export interface FindDevicesResponse { 
    availableCarts?: Array<Cart> | null;
    connectedCarts?: Array<Cart> | null;
    message?: string | null;
}

