/**
 * TeensyRom.Api
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export const TeensyStorageType = {
    NUMBER_0: 0,
    NUMBER_1: 1
} as const;
export type TeensyStorageType = typeof TeensyStorageType[keyof typeof TeensyStorageType];

